


try:
    with ContextManager():
        print('Выполнение блока with')
        raise ValueError
except ValueError:
    print('Исключение обработано')

class ContextManager:
    def __enter__(self):
        print('Вызов метода __enter__()')
    
    def __exit__(self, exc_type, exc_value, traceback):
        print('Вызов метода __exit__()')
        if isinstance(exc_value, ValueError):
            print('Исключение ValueError обработано')
            return True
        return False

class ForgivingIndexer:
    def __init__(self, sequence):
        self.sequence = sequence

    def __getitem__(self, index):
        return self.sequence[int(index)]
    
    def __len__(self):
        return len(self.sequence)



